# Adapted from https://github.com/github/codeql/blob/a448db11b57e7bac553af29fd625c39dd86e45e6/.github/actions/fetch-codeql/action.yml
name: Download CodeQL CLI
description: Fetches the specified version of CodeQL

inputs:
  version:
    required: true

runs:
  using: composite
  steps:
    - name: Fetch CodeQL
      shell: bash
      run: |
        gh release download --repo https://github.com/github/codeql-cli-binaries --pattern codeql-linux64.zip "${{ inputs.version }}"
        unzip -q -d "${RUNNER_TEMP}" codeql-linux64.zip
        echo "${RUNNER_TEMP}/codeql" >> "${GITHUB_PATH}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
